language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
  - pwd
  - mkdir bin
  - ln -s /usr/bin/g++-4.8 bin/g++
  - ln -s /usr/bin/g++-4.8 bin/gcc
  - ln -s /usr/bin/g++-4.8 bin/c++
  - ls -al bin
  - export PATH="/home/travis/build/ethan/simpimc/bin:${PATH}"
  - sudo apt-get install -qq gfortran-4.8
  - export F77="gfortran-4.8"
  - export FC="gfortran-4.8"
  - sudo apt-get install -qq libhdf5-serial-dev
  # - sudo apt-get install -qq libboost-all-dev
  # - sudo apt-get install -qq libarmadillo-dev
  - mkdir include && cd include
  - wget http://downloads.sourceforge.net/project/arma/armadillo-4.450.4.tar.gz
  - tar -xzvf armadillo-4.450.4.tar.gz && cd armadillo-4.450.4
  - mkdir build && cd build
  - cmake ..
  - make && sudo make install && cd ..
  - cd ..
  - export ARMA_HOME=/usr
  - git clone https://github.com/etano/meinspline.git
  - cd meinspline
  - ./configure && make && sudo make install && cd ..
  - export EINSPLINE_HOME=/usr/local
  - cd ..

install:
  - mkdir build && cd build
  - cmake ..
  - cat CMakeCache.txt
  - cat CMakeFiles/simpimc.dir/link.txt
  - which c++
  - ls -al /usr/bin/c++
  - ls -al /etc/alternatives/c++
  - make && make install
  - cd ..

before_script:
  - cd inputs

script: ../bin/simpimc free.xml
