language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - sudo apt-get install -qq gfortran-4.8
  - export F77="gfortran-4.8"
  - export FC="gfortran-4.8"
  - sudo apt-get install -qq libhdf5-serial-dev
  - sudo apt-get install -qq libboost-all-dev
  - sudo apt-get install -qq libarmadillo-dev
  - mkdir include && cd include
  - git clone https://github.com/etano/meinspline.git
  - cd meinspline
  - ./configure && make && sudo make install && cd ..
  - export EINSPLINE_HOME=/usr/local
  - cd ..

install:
  - mkdir build && cd build
  - cmake ..
  - cat CMakeCache.txt
  - cat CMakeFiles/simpimc.dir/link.txt
  - which c++
  - make && make install
  - cd ..

before_script:
  - cd inputs

script: ../bin/simpimc free.xml
