sudo: false

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gfortran-4.8
      - liblapack-dev
      - libopenmpi-dev
      - openmpi-bin
      - libhdf5-serial-dev

git:
    submodules: false

compiler:
  - gcc

before_install:
  - find . -name .gitmodules -type f -print0 | xargs -0 sed -i 's/git@github.com:/https:\/\/github.com\//'
  - git submodule update --init --recursive
  - export CXX="g++-4.8" CC="gcc-4.8"
  - export F77="gfortran-4.8" FC="gfortran-4.8"
  - mkdir bin && cd bin
  - ln -s /usr/bin/g++-4.8 /home/travis/build/etano/simpimc/bin/g++
  - ln -s /usr/bin/gcc-4.8 /home/travis/build/etano/simpimc/bin/gcc
  - ln -s /usr/bin/gfortran-4.8 /home/travis/build/etano/simpimc/bin/gfortran
  - export PATH="/home/travis/build/etano/simpimc/bin:${PATH}"
  - cd ..
  - export HDF5_HOME=/usr

install:
  - mkdir build && cd build && cmake ..
  - make && make install && cd ..

before_script:
  - cd inputs
  - export OMP_PROC_BIND=TRUE
  - export OMP_NUM_THREADS=2

script: ../bin/simpimc test.xml
