language: cpp

compiler:
  - gcc

before_install:
  - mkdir include && cd include
  - sudo apt-get install gfortran
  - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install libarmadillo-dev
  - git clone https://github.com/etano/meinspline.git
  - cd meinspline
  - ./configure && make && sudo make install && cd ..
  - export EINSPLINE_HOME=/usr/local
  - cd ..

install:
  - mkdir build && cd build
  - cmake ..
  - make && make install
  - cd ..

before_script:
  - cd inputs

script: ../bin/simpimc free.xml
